#!/bin/bash
# scripts by thyeun

## Get data
STATUS=$(playerctl --player=$Control status)
Cover=/tmp/.music_cover.png
MUSIC_DIR="$HOME/Music"
# if cover not found in metadata use this instead
bkpCover=~/.config/eww/bar/images/music.png
Control="MPD"
[ -n "$(pgrep tauon)" ] && Control="tauon"

## Get status
get_status() {
icon=""
[ $(playerctl --player=$Control status) = "Playing" ] && icon=""
[ $(playerctl --player=$Control status) = "Paused" ] && icon="奈"
echo "$icon"
}

## Get song
get_song() {
	song=$(playerctl --player=$Control metadata --format {{title}})
	if [[ -z "$song" ]]; then
		echo "Offline"
	else
		echo "$song"
	fi	
}

## Get artist
get_artist() {
	artist=$(playerctl --player=$Control metadata --format {{artist}})
	if [[ -z "$artist" ]]; then
		echo ""
	else
		echo "$artist"
	fi	
}

get_ctime() {
	ctime=$(playerctl --player=$Control position --format "{{ duration(position) }}")
	if [[ -z "$ctime" ]]; then
		echo "0:00"
	else
		echo "$ctime"
	fi	
}

## Get cover
get_cover() {
albumart="$(playerctl --player=$Control metadata mpris:artUrl | sed -e 's/open.spotify.com/i.scdn.co/g')"
[ $(playerctl --player=$Control metadata mpris:artUrl) ] && curl -s "$albumart" --output $Cover || cp $bkpCover $Cover 
echo "$Cover"
}

## Execute accordingly
if [[ "$1" == "--song" ]]; then
	get_song
elif [[ "$1" == "--artist" ]]; then
	get_artist
elif [[ "$1" == "--status" ]]; then
	get_status
elif [[ "$1" == "--ctime" ]]; then
	get_ctime
elif [[ "$1" == "--cover" ]]; then
	get_cover
elif [[ "$1" == "--toggle" ]]; then
	playerctl --player=$Control play-pause
elif [[ "$1" == "--next" ]]; then
	playerctl --player=$Control next;get_cover
elif [[ "$1" == "--prev" ]]; then
	playerctl --player=$Control previous; get_cover
fi
